services:
  - type: pserv
    name: clickhouse
    env: docker
    plan: standard
    region: frankfurt
    autoDeploy: false
    disk:
      name: data
      mountPath: /var/lib/clickhouse
      sizeGB: 10
